In [49]:
! pip install pandas pymysql sqlalchemy
! pip install mysql-connector-python
! pip install streamlit

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\dell\appdata\roaming\python\python311\site-packages (3.0.5)
Requirement already satisfied: pymysql in c:\users\dell\appdata\roaming\python\python311\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\roaming\python\python311\site-packages (2.0.52)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\roaming\python\python311\site-packages (from pandas) (2026.3)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\roaming\python\python311\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\dell\appdata\roaming\python\python311\site-packages (26.7.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in c:\users\dell\appdata\roaming\python\python311\site-packages (1.62.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (2.4.6)
Requirement already satisfied: packaging>=20 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (3.0.5)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (12.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (7.36.0)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (25.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette<2,>=0.46.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (0.52.4)
Requirement already satisfied: httptools<1,>=0.6.3 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (16.1.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\dell\appdata\roaming\python\python311\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.25.0)
Requirement already satisfied: idna>=2.8 in c:\users\dell\appdata\roaming\python\python311\site-packages (from anyio<5,>=4.0.0->streamlit) (3.19)
Requirement already satisfied: colorama in c:\users\dell\appdata\roaming\python\python311\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python311\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\roaming\python\python311\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\roaming\python\python311\site-packages (from requests<3,>=2.27->streamlit) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\dell\appdata\roaming\python\python311\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\dell\appdata\roaming\python\python311\site-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in c:\users\dell\appdata\roaming\python\python311\site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\dell\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\dell\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\dell\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:

df = pd.read_csv('global_seismic_trends_miniproject1.csv')
engine = create_engine('mysql+pymysql://root:gold90038%40@localhost:3306/global_seismic_trends')
df.to_sql('earthquakes', con=engine, if_exists='replace', index=False)

117824

In [43]:
import mysql.connector
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="gold90038@",
    database="global_seismic_trends",
)
cursor = conn.cursor()

In [44]:
#1. Top 10 strongest earthquakes (mag).

qus1="""select * from earthquakes 
order by mag desc 
limit 10;"""

df1=pd.read_sql(qus1,engine)
df1

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,gap,type,year,month,day,day_of_week,hour,depth_catagory,mag_type_flag,country
0,us6000qw60,2025-07-29 23:24:52.483,52.4948,160.2395,35.000,8.8,mww,"2025 kamchatka peninsula, russia earthquake",reviewed,1,...,30.0,earthquake,2025,july,29,tuesday,23,shallow,destructive,russian federation
1,ak0219neiszm,2021-07-29 06:15:49.188,55.3635,-157.8876,35.000,8.2,mww,"2021 chignik, alaska earthquake",reviewed,1,...,113.0,earthquake,2021,july,29,thursday,6,shallow,destructive,united states
2,us7000dflf,2021-03-04 19:28:33.178,-29.7228,-177.2794,28.930,8.1,mww,"2021 kermadec islands, new zealand earthquake",reviewed,1,...,21.0,earthquake,2021,march,4,thursday,19,shallow,destructive,tonga
3,us6000f53e,2021-08-12 18:35:17.231,-58.3753,-25.2637,22.790,8.1,mww,2021 south sandwich islands earthquake,reviewed,0,...,78.0,earthquake,2021,august,12,thursday,18,shallow,destructive,south georgia and the south sandwich islands
4,us6000jllz,2023-02-06 01:17:34.342,37.2256,37.0143,10.000,7.8,mww,"pazarcik earthquake, kahramanmaras earthquake ...",reviewed,0,...,17.0,earthquake,2023,february,6,monday,1,shallow,destructive,türkiye
5,us7000qx2g,2025-09-18 18:58:14.939,53.1426,160.7206,27.000,7.8,mww,"140 km e of petropavlovsk-kamchatsky, russia",reviewed,1,...,76.0,earthquake,2025,september,18,thursday,18,shallow,destructive,russian federation
6,us7000srb1,2026-06-07 23:37:41.970,5.5994,125.0560,56.991,7.8,mww,"25 km sw of kablalan, philippines",reviewed,0,...,21.0,earthquake,2026,june,7,sunday,23,shallow,destructive,philippines
7,us6000tkt2,2026-08-14 21:58:21.564,-8.3101,121.3517,10.000,7.7,mww,"68 km nnw of ende, indonesia",reviewed,0,...,36.0,earthquake,2026,august,14,friday,21,shallow,destructive,indonesia
8,us7000pn9s,2025-03-28 06:20:52.715,22.0110,95.9363,10.000,7.7,mww,"2025 mandalay, burma (myanmar) earthquake",reviewed,0,...,24.0,earthquake,2025,march,28,friday,6,shallow,destructive,myanmar
9,us6000dg77,2021-02-10 13:19:55.530,-23.0511,171.6566,10.000,7.7,mww,southeast of the loyalty islands,reviewed,1,...,15.0,earthquake,2021,february,10,wednesday,13,shallow,destructive,new caledonia

In [7]:
#2. Top 10 deepest earthquakes (depth_km).

qus2="""select * from earthquakes 
order by depth_km DESC 
limit 10;"""
df2=pd.read_sql(qus2,conn)

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\1140065340.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2=pd.read_sql(qus2,conn)

In [8]:
# 3. Shallow earthquakes < 50 km and mag > 7.5.

qus3="""select * from earthquakes 
where depth_km < 50 and mag > 7.5;"""
df3=pd.read_sql(qus3,conn)

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\3677720058.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df3=pd.read_sql(qus3,conn)

In [10]:
# 5. Average magnitude per magnitude type (magType).

qus5="""select magType, avg(mag) as avg_magnitude 
from earthquakes 
group by magType;"""
df5=pd.read_sql(qus5,conn)
df5

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\1545489965.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df5=pd.read_sql(qus5,conn)

       magType  avg_magnitude
0          mwr       4.324376
1           mb       4.423668
2           md       3.438873
3          mww       5.367372
4           ml       3.275267
5           mw       3.939501
6          mwb       5.787500
7        mb_lg       3.201587
8          mwc       6.150000
9          mlr       3.480000
10         mlg       3.300000
11       ms_20       5.800000
12         mlv       3.469288
13  ml(texnet)       3.367442
14       ms_vx       4.600000
15         mwp       5.250000
16          mh       4.100000

In [11]:
# 6. Year with most earthquakes.

qus6="""select year,count(*) as total_counts
from earthquakes 
group by year 
order by total_counts desc
limit 1;"""
df6=pd.read_sql(qus6,conn)
df6

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\223372306.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df6=pd.read_sql(qus6,conn)

   year  total_counts
0  2025         22818

In [12]:
# 7. Month with highest number of earthquakes.

qus7="""select month,count(*) AS total_counts
from earthquakes 
group by month
order by total_counts DESC 
limit 1;"""
df7=pd.read_sql(qus7,conn)
df7

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\3959811047.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df7=pd.read_sql(qus7,conn)

  month  total_counts
0  july         11724

In [13]:
# 8. Day of week with most earthquakes.

qus8="""select day_of_week,count(*) as total_earthquakes 
from earthquakes 
group by day_of_week 
order by total_earthquakes desc
limit 1;"""
df8=pd.read_sql(qus8,conn)
df8

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\3776260508.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df8=pd.read_sql(qus8,conn)

  day_of_week  total_earthquakes
0      friday              17034

In [45]:
#9. Count of earthquakes per hour of day.

qus9="""select hour,count(*) AS total_counts
from earthquakes 
group by hour 
order by total_counts;"""
df9=pd.read_sql(qus9,conn)
df9

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\1610188289.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df9=pd.read_sql(qus9,conn)

    hour  total_counts
0     12          4607
1     11          4635
2     14          4704
3     10          4738
4      6          4750
5     16          4753
6      5          4835
7     15          4846
8     13          4852
9      9          4862
10     0          4869
11    23          4883
12    17          4894
13     7          4898
14    18          4919
15     8          4923
16    19          4978
17     2          5000
18    20          5007
19    22          5107
20     4          5162
21     1          5170
22    21          5215
23     3          5217

In [15]:
# 10.   Most active reporting network (net).

qus10="""select net, count(*) as total_reports 
from earthquakes 
group by net 
order by total_reports desc
limit 1;"""
df10=pd.read_sql(qus10,conn)
df10

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\1535552846.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df10=pd.read_sql(qus10,conn)

  net  total_reports
0  us         102978

In [16]:
#  11.  Top 5 places with highest casualties.
qus11="""select place, max(sig) as max_impact
from earthquakes 
group by place 
order by max_impact desc
limit 5;"""
df11=pd.read_sql(qus11,conn)
df11

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\2464118164.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df11=pd.read_sql(qus11,conn)

                                               place  max_impact
0          2025 mandalay, burma (myanmar) earthquake        2910
1  pazarcik earthquake, kahramanmaras earthquake ...        2910
2            5 km s of san josé del palmar, colombia        2790
3           2025 southern tibetan plateau earthquake        2787
4                 20 km w of catia la mar, venezuela        2739

In [17]:
# 13.  Average economic loss by alert level.

qus13="""select alert,avg(sig) as  avg_impact
from earthquakes 
group by alert;"""
df13=pd.read_sql(qus13,conn)
df13

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\3532274761.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df13=pd.read_sql(qus13,conn)

    alert  avg_impact
0   green    286.1662
1  yellow    769.9753
2  orange   1175.2692
3     red   2273.0357

In [18]:
#  14.  Count of reviewed vs automatic earthquakes (status).
qus14="""select status, count(*) as total_count 
from earthquakes 
group by status;"""
df14=pd.read_sql(qus14,conn)
df14

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\560014970.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df14=pd.read_sql(qus14,conn)

      status  total_count
0   reviewed       117659
1  automatic          165

In [19]:
#  15.  Count by earthquake type (type).
qus15="""select type, count(*) as total_count 
from earthquakes 
group by type;"""
df15=pd.read_sql(qus15,conn)
df15

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\4021785401.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df15=pd.read_sql(qus15,conn)

                     type  total_count
0              earthquake       116929
1        mining explosion          850
2               ice quake           13
3  experimental explosion            5
4           mine collapse            3
5            quarry blast            2
6       volcanic eruption           12
7               landslide            4
8             other event            5
9               explosion            1

In [20]:
#  16.  Number of earthquakes by data type (types).

qus16="""select types, count(*) as total_count 
from earthquakes 
group by types;"""
df16=pd.read_sql(qus16,conn)
df16

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\31148548.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df16=pd.read_sql(qus16,conn)

                                                 types  total_count
0                 dyfi,moment-tensor,origin,phase-data         1370
1                                    origin,phase-data        89595
2    dyfi,impact-text,internal-origin,losspager,mom...            8
3                               dyfi,origin,phase-data         8962
4                      moment-tensor,origin,phase-data         1397
..                                                 ...          ...
571              dyfi,general-header,origin,phase-data            2
572  associate,dyfi,earthquake-name,finite-fault,ge...            1
573  dyfi,event-sequence,focal-mechanism,losspager,...            1
574  dyfi,event-sequence,finite-fault,general-text,...            2
575  dyfi,event-sequence,moment-tensor,oaf,origin,p...            1

[576 rows x 2 columns]

In [21]:
#18.  Events with high station coverage (nst > threshold).

qus18="""select * from earthquakes 
where nst > 100 
order by nst desc 
limit 5;"""
df18=pd.read_sql(qus18,conn)
df18

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\1196641103.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df18=pd.read_sql(qus18,conn)

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,gap,type,year,month,day,day_of_week,hour,depth_catagory,mag_type_flag,country
0,us6000m12f,2024-01-02 01:17:31.568,37.2470,136.7689,6.000,5.4,mww,"11 km w of anamizu, japan",reviewed,0,...,26.0,earthquake,2024,january,2,tuesday,1,shallow,normal,japan
1,us6000qzfl,2025-08-09 08:01:41.017,51.7700,158.1810,70.157,5.0,mww,"120 km ene of ozernovskiy, russia",reviewed,0,...,114.0,earthquake,2025,august,9,saturday,8,intermediate,normal,russian federation
2,us7000rluk,2026-01-01 06:46:54.742,60.5362,-140.0494,5.000,5.7,mww,"111 km n of yakutat, alaska",reviewed,1,...,42.0,earthquake,2026,january,1,thursday,6,shallow,normal,canada
3,us7000pvtr,2025-04-29 14:53:37.897,-54.2616,155.6446,18.957,6.8,mww,macquarie island region,reviewed,1,...,11.0,earthquake,2025,april,29,tuesday,14,shallow,storng,australia
4,usd001097k,2023-12-11 18:35:59.877,-24.0849,-66.7812,191.769,5.5,mww,"49 km wnw of san antonio de los cobres, argentina",reviewed,0,...,51.0,earthquake,2023,december,11,monday,18,intermediate,normal,argentina

In [22]:
#19.  Number of tsunamis triggered per year.
qus19="""select year,count(*)  as tsunami_count 
from earthquakes 
where tsunami = 1
group by year;"""
df19=pd.read_sql(qus19,conn)
df19

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\2967709599.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df19=pd.read_sql(qus19,conn)

   year  tsunami_count
0  2021            114
1  2022            136
2  2023            119
3  2024            114
4  2025            142
5  2026             34

In [23]:
#20. 20.  Count earthquakes by alert levels (red, orange, etc.).

qus20="""select alert, count(*) as total_count 
from earthquakes 
group by alert;"""
df20=pd.read_sql(qus20,conn)
df20

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\295918315.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df20=pd.read_sql(qus20,conn)

    alert  total_count
0   green       117608
1  yellow          162
2  orange           26
3     red           28

In [26]:
#21.Find the top 5 countries with the highest average magnitude of earthquakes in the past 5 years  
qus21="""select country, avg(mag) as avg_mag 
from earthquakes 
where year>=(select max(year)-5 from earthquakes)
group by country
order by avg_mag desc 
limit 5;"""
df21=pd.read_sql(qus21,conn)
df21

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\1507410572.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df21=pd.read_sql(qus21,conn)

          country   avg_mag
0      cabo verde  5.300000
1           nauru  5.000000
2  norfolk island  4.966667
3        pitcairn  4.953535
4        malaysia  4.942857

In [46]:
# 22.Find countries that have experienced both shallow and deep earthquakes within the same month.
qus22="""select country, year,month 
from earthquakes 
group by country, year, month 
having sum(case when depth_km< 70 then 1 else 0 end) > 0 
   and sum(case when depth_km > 300 then 1 else 0 end) > 0;"""
df22=pd.read_sql(qus22,conn)
df22

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\650828629.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df22=pd.read_sql(qus22,conn)

                      country  year    month
0           wallis and futuna  2021  january
1                 philippines  2021  january
2                   indonesia  2021  january
3    northern mariana islands  2021  january
4                     vanuatu  2021  january
..                        ...   ...      ...
705                     japan  2026   august
706                 indonesia  2026   august
707                     tonga  2026   august
708  northern mariana islands  2026   august
709                   vanuatu  2026   august

[710 rows x 3 columns]

In [28]:
# 23.Compute the year-over-year growth rate in the total number of earthquakes globally.

qus23="""with yearlycounts as (
    select year as eq_year, count(*) as total_eq 
    from earthquakes 
    group by year
)
select eq_year, total_eq,
    lag(total_eq) over (order by eq_year) as prev_year_total,
    round(((total_eq - lag(total_eq) over (order by eq_year)) / lag(total_eq) over (order by eq_year)) * 100, 2) as yoy_growth_percent
from yearlyCounts;"""
df23=pd.read_sql(qus23,conn)
df23

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\1906414172.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df23=pd.read_sql(qus23,conn)

   eq_year  total_eq  prev_year_total  yoy_growth_percent
0     2021     21926              NaN                 NaN
1     2022     20208          21926.0               -7.84
2     2023     20830          20208.0                3.08
3     2024     18659          20830.0              -10.42
4     2025     22818          18659.0               22.29
5     2026     13383          22818.0              -41.35

In [29]:
#24. List the 3 most seismically active regions by combining both frequency and average magnitude.
qus24="""select place, count(*) as frequency, avg(mag) as avg_mag 
from earthquakes 
group by place 
order by (count(*) * avg(mag)) desc 
limit 3;"""
df24=pd.read_sql(qus24,conn)
df24

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\2371344992.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df24=pd.read_sql(qus24,conn)

                           place  frequency   avg_mag
0  south sandwich islands region       3181  4.681125
1        kermadec islands region       1964  4.646319
2      south of the fiji islands       2049  4.444607

In [31]:
#  25. For each country, calculate the average depth of earthquakes within ±5° latitude range of the equator.
qus25="""select country, avg(depth_km) as avg_depth 
from earthquakes 
where latitude between -5 and 5 
group by country;"""
df25=pd.read_sql(qus25,conn)
df25

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\2092052144.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df25=pd.read_sql(qus25,conn)

                                         country   avg_depth
0                                      indonesia   64.736561
1                                         guyana   10.351429
2                                        ecuador   39.817092
3   saint helena, ascension and tristan da cunha   10.000000
4                                       colombia   42.645762
5          congo, the democratic republic of the    9.918292
6                               papua new guinea   72.692668
7                                        burundi   10.000000
8                                       maldives   10.034157
9                                         panama   10.348318
10                                          peru   59.542735
11                                        brazil   10.019955
12               micronesia, federated states of   11.018000
13                                        uganda   10.237679
14                  tanzania, united republic of   10.000000
15                                   philippines  158.133603
16                                         gabon    9.818182
17                                        rwanda   10.441538
18                                       tokelau   10.000000
19                                      kiribati   10.000000
20                                   south sudan   10.000000
21                                     sri lanka   10.000000
22                                       liberia   10.000000
23                                         palau   10.000000
24                                         yemen   10.000000
25                                      ethiopia   10.000000
26                                      malaysia   10.762500
27                                  sierra leone   10.000000
28                                    costa rica   10.000000
29                                         nauru   10.000000
30                                         kenya    9.866000
31                                        mexico   10.000000
32             venezuela, bolivarian republic of   11.127000
33                                 côte d'ivoire   10.000000
34                             equatorial guinea   10.000000

In [33]:
# 26. Identify countries having the highest ratio of shallow to deep earthquakes.
qus26="""select country, 
    sum(case when depth_km < 70 then 1 else 0 end) / 
    nullif(sum(case when depth_km > 300 then 1 else 0 end), 0) as shallow_to_deep_ratio 
from earthquakes 
group by country 
order by shallow_to_deep_ratio desc;"""
df26=pd.read_sql(qus26,conn)
df26

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\872036893.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df26=pd.read_sql(qus26,conn)

                  country  shallow_to_deep_ratio
0                   china                940.000
1             afghanistan                276.000
2                    guam                249.500
3                    peru                190.250
4         solomon islands                104.125
..                    ...                    ...
188            montserrat                    NaN
189           netherlands                    NaN
190  united arab emirates                    NaN
191          cook islands                    NaN
192               denmark                    NaN

[193 rows x 2 columns]

In [34]:
#27. Find the average magnitude difference between earthquakes with tsunami alerts and those without.
qus27="""select (select avg(mag) from earthquakes where tsunami=1)-(
select avg(mag) from earthquakes where tsunami=0) as avg_magnitude_diff;"""
df27=pd.read_sql(qus27,conn)
df27

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\2606507902.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df27=pd.read_sql(qus27,conn)

   avg_magnitude_diff
0            1.166969

In [48]:
#28. Using the gap and rms columns, identify events with the lowest data reliability (highest average error margins).
qus28="""select *, (gap + rms) as total_error_margin 
from earthquakes 
order by total_error_margin desc 
limit 10;"""
df28=pd.read_sql(qus28,conn)
df28

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\3465581999.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df28=pd.read_sql(qus28,conn)

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,type,year,month,day,day_of_week,hour,depth_catagory,mag_type_flag,country,total_error_margin
0,pr71519528,2026-06-11 12:21:59.730,18.571833,-63.922333,62.92,3.31,md,"95 km ene of cruz bay, u.s. virgin islands",reviewed,0,...,earthquake,2026,june,11,thursday,12,shallow,normal,"virgin islands, british",359.1400
1,nn00897599,2025-05-14 12:02:09.568,41.217000,-116.681700,0.00,3.00,ml,"60 km ne of valmy, nevada",reviewed,0,...,earthquake,2025,may,14,wednesday,12,shallow,normal,united states,358.3401
2,pr2024051000,2024-02-20 05:23:09.140,18.615600,-63.676800,30.00,3.58,md,"77 km nw of sandy ground village, anguilla",reviewed,0,...,earthquake,2024,february,20,tuesday,5,shallow,normal,anguilla,358.1600
3,pr71508583,2026-02-23 19:35:44.000,18.578333,-63.809500,42.82,3.17,md,"86 km wnw of sandy ground village, anguilla",reviewed,0,...,earthquake,2026,february,23,monday,19,shallow,normal,"virgin islands, british",356.2200
4,us7000denb,2021-02-14 19:26:12.202,51.291100,-179.245100,35.00,3.30,ml,"andreanof islands, aleutian islands, alaska",reviewed,0,...,earthquake,2021,february,14,sunday,19,shallow,normal,united states,355.3400
5,aka2026fwzivr,2026-03-25 08:04:49.491,54.686000,-144.267000,5.00,3.90,ml,south of alaska,automatic,0,...,earthquake,2026,march,25,wednesday,8,shallow,normal,united states,354.7000
6,pr2022227000,2022-08-15 01:27:45.500,18.484300,-64.252300,14.00,3.63,md,"59 km ene of cruz bay, u.s. virgin islands",reviewed,0,...,earthquake,2022,august,15,monday,1,shallow,normal,"virgin islands, british",353.6100
7,pr71489653,2025-07-18 23:19:06.230,17.907000,-68.719000,46.94,3.13,md,"53 km ssw of boca de yuma, dominican republic",reviewed,0,...,earthquake,2025,july,18,friday,23,shallow,normal,dominican republic,352.1800
8,pr2022289000,2022-10-16 20:43:51.670,18.341500,-64.049000,44.00,3.48,md,"78 km e of cruz bay, u.s. virgin islands",reviewed,0,...,earthquake,2022,october,16,sunday,20,shallow,normal,"virgin islands, british",352.0700
9,pr2021003002,2021-01-03 01:55:58.430,18.036300,-63.958100,32.00,3.53,md,"87 km wnw of the bottom, bonaire, saint eustat...",reviewed,0,...,earthquake,2021,january,3,sunday,1,shallow,normal,"virgin islands, british",351.4400

In [47]:
# 30. Determine the regions with the highest frequency of deep-focus earthquakes (depth > 300 km).
qus30="""select place, count(*) as deep_earthquake_count 
from earthquakes 
where depth_km > 300 
group by place 
order by deep_earthquake_count desc;"""
df30=pd.read_sql(qus30,conn)
df30

C:\Users\Dell\AppData\Local\Temp\ipykernel_26972\310792245.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df30=pd.read_sql(qus30,conn)

                                place  deep_earthquake_count
0           south of the fiji islands                   1722
1                         fiji region                   1285
2             kermadec islands region                    167
3         bonin islands, japan region                    140
4           izu islands, japan region                    111
...                               ...                    ...
1888        165 km n of sola, vanuatu                      1
1889      173 km ene of sola, vanuatu                      1
1890       180 km ne of sola, vanuatu                      1
1891  108 km nnw of batang, indonesia                      1
1892    54 km ese of isangel, vanuatu                      1

[1893 rows x 2 columns]